### ISSUE TITLE
Content width on mobile devices

### ISSUE THREAD

**Issue by marktnoonan** [FrontendMasters/front-end-handbook-2019#13]
Hi! At Brent's suggestion, I'm opening this issue: on my iPhone 6 the book slides around to the left and right as I scroll, and if I zoom out I can see that some content is too wide - long words in the headings, or sections of URLs that don't have dashes where the text would be able to break. This also creates more width for the table in the screenshot below, meaning that it takes up more space than is available on the screen.

My suggest is fix is a broad one but doesn't seem to cause any problems: adding word-break: break-all to the body css rule. I'll submit a PR for this. Thank you for this amazing free resource, I'll be reading it myself but also sharing it with folks I know who are newer to programming.

![IMG_1138](https://user-images.githubusercontent.com/8340719/56083770-87504200-5df7-11e9-8944-1f4ecd01180b.PNG)
![IMG_1137](https://user-images.githubusercontent.com/8340719/56083771-87504200-5df7-11e9-8914-d1889a8f300e.PNG)
![IMG_1136](https://user-images.githubusercontent.com/8340719/56083772-87504200-5df7-11e9-8f45-974ee4687d67.PNG)

**Comment by 1Marc** [comment]
Thanks! Merged.
