### ISSUE TITLE
i18n support plan ?

### ISSUE THREAD

**Issue by itning** [FrontendMasters/front-end-handbook-2019#15]
Suggest you create translate progect on 
<https://poeditor.com/>

**Comment by 1Marc** [comment]
I agree we should have a plan for internationalization, but we don't have time to setup and manage this right now... if someone from the community submits a PR with translations that we can include on the site, that would be more helpful.

**Comment by neekychan** [comment]
Here the chinese version
https://github.com/neekychan/front-end-handbook-2019
