### ISSUE TITLE
HTTP RFC

### ISSUE THREAD

**Issue by detj** [FrontendMasters/front-end-handbook-2019#3]
The HTTP RFC link is RFC 2616, which has been superseded by the RFC 723x family. Should we mention that? Or maybe only mention the 723x RFCs

[Message Syntax and Routing](https://tools.ietf.org/html/rfc7230)
[Semantics and Content](https://tools.ietf.org/html/rfc7231)
[Conditional Requests](https://tools.ietf.org/html/rfc7232)
[Range Requests](https://tools.ietf.org/html/rfc7233)
[Caching](https://tools.ietf.org/html/rfc7234)
[Authentication](https://tools.ietf.org/html/rfc7235)

**Comment by 1Marc** [comment]
Can you please submit a pull request with your suggestion @detj ? I don't know what to do here.

**Comment by detj** [comment]
@1Marc Sorry for the late reply. Here's the PR #55
