### ISSUE TITLE
Where's the iBooks / E-book download?

### ISSUE THREAD

**Issue by tr1s** [FrontendMasters/front-end-handbook-2019#33]

**Comment by anevins12** [comment]
There is none and that issue was closed 5 days ago https://github.com/FrontendMasters/front-end-handbook-2019/issues/9

**Comment by 1Marc** [comment]
Thanks @anevins12. As I stated in #9, the handbook is just plain HTML -- there are a million services to turn HTML into epub, PDF... or whatever format you need.

I used https://dotepub.com to create a `.epub` file in less than a minute from googling "how to turn HTML into an epub" to finding the service and using the bookmarklet to generate the file.

**Comment by tr1s** [comment]
I mean you all went through the trouble to create this massive resource, but decided to not spend the extra minute to create an epub/pdf download file so people could enjoy this offline?

I have the 2017 and 2018 versions for iBooks that I downloaded officially, so I assumed this was an oversight. Adding the downloads probably would have saved you more time than answering GitHub issues asking where it is lol just saying 🤷🏽‍♂️

**Comment by anevins12** [comment]
Hey that's a bit unfair. I thought the same, but instead of just creating an issue I created a pull request and now there are print stylesheets. So just preview it in your browser and save as PDF, done, it doesn't even take the minute you suggest.

**Comment by tr1s** [comment]
What's unfair is @1Marc telling people "there's a million services" to convert and "it only takes a minute" when we're just trying to point out an oversight. It's not a matter of how easy it is, it's a matter of user experience. Who's first instinct is it to use the "print" feature? That's 90's/2000's era. I tried to right-click save-as and was presented with a popup that wants me to save a webpage. Not useful. On top of that, converting to epub/ibooks is even less straightforward. You have to google it and decipher x number of sketchy poorly designed websites to convert it. Obviously I can figure it out, that's not the point though.

Take a look at 2018's version. A clear and concise introduction with options to download before you even get into it. 2019 has no introduction and no downloads, and already has 3 people creating issues and more people inside those issues wondering where the download is. But if y'all want to keep answering the same questions on GitHub and telling people how easy it is, you do you!

<img width="1227" alt="CleanShot 2019-04-23 at 15 56 12@2x" src="https://user-images.githubusercontent.com/19172250/56611700-70240800-65e0-11e9-8584-b906809e60ec.png">

**Comment by 1Marc** [comment]
Added download links to the [README](https://github.com/FrontendMasters/front-end-handbook-2019).

Downside is now I have to regenerate these files every time I maintain/update the repo, so using File -> Export as PDF or an HTML to ePub converter will ensure you have the latest content.
