### ISSUE TITLE
Accessibility resource

### ISSUE THREAD

**Issue by nico3333fr** [FrontendMasters/front-end-handbook-2019#44]
Hi there,

may I suggest one resource for accessibility: The AcceDe Web guides https://www.accede-web.com/en/ ?

This is a fantastic resource and very practical to learn accessibility.

Cheers,
Nicolas

**Comment by dragan1700** [comment]
May I suggest to add the [Accessibility Developer Guide](https://www.accessibility-developer-guide.com/) as well to https://frontendmasters.com/books/front-end-handbook/2019/#4.14 ?
