### ISSUE TITLE
Unaccessible link

### ISSUE THREAD

**Issue by CharlieStras** [FrontendMasters/front-end-handbook-2019#47]
Hi,

When I clicked [What Is the Internet? Or, 'You Say Tomato, I Say TCP/IP'](http://www.20thingsilearned.com/en-US/what-is-the-internet/1), it redirected to Google's home page.

I don't know if the link is dead or by some other reason.

**Comment by detj** [comment]
@CharlieStras Yes. 20thingsilearned.com domain now responds with a 301 Moved Permanently to https://www.google.com/

@1Marc Shall we remove this entry? I couldn't find any alternative host for this web page. Just this [blog post](https://googleblog.blogspot.com/2010/11/curious-guide-to-browsers-and-web.html) about it.

**Comment by detj** [comment]
@codylindley what do you think?
