### ISSUE TITLE
Hoisting instead of hosting

### ISSUE THREAD

**Issue by ryanjohnston** [FrontendMasters/front-end-handbook-2019#48]
I believe that in the diagram, it should be "hoisting" under JavaScript instead of "hosting"

![hoisting](https://user-images.githubusercontent.com/137759/56850635-7b1db780-68c2-11e9-936e-3fc6252b2810.png)
.

**Comment by detj** [comment]
@1Marc Can we merge this?

**Comment by codylindley** [comment]
This is a third-party resource. https://github.com/kamranahmedse/developer-roadmap
