### ISSUE TITLE
Web Assembly

### ISSUE THREAD

**Issue by fairmutex** [FrontendMasters/front-end-handbook-2019#54]
Worth mentioning
https://webassembly.org/docs/high-level-goals/

Some already use it
https://www.smashingmagazine.com/2019/04/webassembly-speed-web-app/

Microsoft shipped their first version
https://dotnet.microsoft.com/apps/aspnet/web-apps/client

**Comment by 1Marc** [comment]
For sure will be featured in the 2020 handbook! cc @codylindley
