### ISSUE TITLE
Page link is 404!

### ISSUE THREAD

**Issue by dujuanxian** [FrontendMasters/front-end-handbook-2019#59]
https://frontendmasters.com/books/front-end-handbook/2019/
The link is 404 currently, is it moved?

**Comment by ejachang** [comment]
@dujuanxian I think it's working now
<img width="1273" alt="Screen Shot 2019-11-05 at 22 40 47" src="https://user-images.githubusercontent.com/32560445/68274199-521e7200-001d-11ea-8750-1c66397a4b4a.png">
