### ISSUE TITLE
Creating HTML5 Offline Web Applications [read]

### ISSUE THREAD

**Issue by aesyondu** [FrontendMasters/front-end-handbook-2019#61]
https://github.com/FrontendMasters/front-end-handbook-2019/blob/6a9b993d93f38c67442d39cfe167b983848dc31b/open-in-web-browser.html#L2538

Link doesn't work for me:

[Creating HTML5 Offline Web Applications [read] ](http://apress.jensimmons.com/v5/pro-html5-programming/ch12.html)

**Comment by sinozzuke** [comment]
For me neither, the whole site is down.

**Comment by 1Marc** [comment]
Removed.
