### ISSUE TITLE
Please add pdf vesion of the ebook

### ISSUE THREAD

**Issue by Donboscow** [FrontendMasters/front-end-handbook-2019#9]
It would be great to have a pdf version of the ebook.

**Comment by 1Marc** [comment]
You can do a file -> save as HTML to take it offline. I don't think it needs to be a PDF unless I'm missing something? What is the use case?

**Comment by roohix** [comment]
it will be use for iPad  or EBook reader
is a standard format and portable for every where specially for travel

**Comment by 1Marc** [comment]
In safari I closed the menu and did **File** -> **Export as PDF** and it looks fine to me. In the future you'll want to do this yourself to get the latest PDF with the updated content, but I did this now and here was the results:

[Front-End-Developer Handbook-2019.pdf](https://github.com/FrontendMasters/front-end-handbook-2019/files/3085918/Front-End-Developer.Handbook-2019.pdf)

**Comment by dhruvdutt** [comment]
@1Marc Where can I find `.epub` version? My use-case is to use it with macOS Books app.

**Comment by 1Marc** [comment]
As I stated in #33, the handbook is just plain HTML -- there are a million services to turn HTML into epub, PDF... or whatever format you need.

I used https://dotepub.com to create a .epub file in less than a minute from googling "how to turn HTML into an epub" to finding the service and using the bookmarklet to generate the file.

**Comment by 1Marc** [comment]
Added download links to the [README](https://github.com/FrontendMasters/front-end-handbook-2019).

Downside is now I have to regenerate these files every time I maintain/update the repo, so using File -> Export as PDF or an HTML to ePub converter will ensure you have the latest content.
